# permissions for end users to edit whisperers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whisperer-editor-role
rules:
- apiGroups:
  - shipyard.shipyard.dev
  resources:
  - whisperers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipyard.shipyard.dev
  resources:
  - whisperers/status
  verbs:
  - get
