# permissions for end users to view whisperers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whisperer-viewer-role
rules:
- apiGroups:
  - shipyard.shipyard.dev
  resources:
  - whisperers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipyard.shipyard.dev
  resources:
  - whisperers/status
  verbs:
  - get
